<?php
namespace Electro\Interfaces\Migrations;

/**
 * A class that implements a single seeder.
 */
interface SeederInterface
{
  /**
   * Returns the SQL queries generated by the seeder.
   *
   * @return string[]
   */
  function getQueries ();

  /**
   * Checks if the output is muted (disabled).
   *
   * @return bool
   */
  function isMuted ();

  /**
   * @param bool $muted [optional] true (or ommitted) to mute (disable) the output, false to unmute it.
   */
  function mute ($muted = true);

  /**
   * Runs the seeder.
   */
  function run ();

  /**
   * Configuration options for the seeding process.
   *
   * @param array $options <dl>
   *                       <dt>'pretend' => bool
   *                       <dd>If true, the seeder is not actually run and the SQL code that would be executed is
   *                       returned.
   *                       <dt>'clear' => bool
   *                       <dd>if true, data is cleared from each target table before it's seeded.
   *                       </dl>
   */
  function setOptions (array $options);

}
